# Generated by Django 5.1.6 on 2025-03-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(default="Unknown", max_length=300),
        ),
    ]
